### ISSUE TITLE
emu broke itself

### ISSUE THREAD

**Issue by Sprosenax** [real-pmein1/stmsrvemu#32]
it was working other day and now it doesn't and no i didn't downloaded or updated anything

2024-08-15 15:14:55,460 emulator     INFO     ...Starting Steam Server...
2024-08-15 15:14:55,525 emulator     INFO     Checking for gcf files to convert...
E2xception in thread Thread-1:
Traceback (most recent call last):
  File "c:\python27_86\lib\threading.py", line 801, in __bootstrap_inner
  File "Y:\source\Server\emulator.py", line 339, in run
  File "Y:\source\Server\steam.py", line 703, in bind
  File "c:\python27_86\lib\socket.py", line 228, in meth
error: [Errno 10049] ¦stenen adres ieri­inde geerli de­il
024-08-15 15:14:55,734 emulator     INFO     Steam2 CSER Server listening on port 27013

E2xception in thread Thread-2:
Traceback (most recent call last):
  File "c:\python27_86\lib\threading.py", line 801, in __bootstrap_inner
  File "Y:\source\Server\emulator.py", line 319, in run
  File "Y:\source\Server\steam.py", line 703, in bind
  File "c:\python27_86\lib\socket.py", line 228, in meth
error: [Errno 10049] ¦stenen adres ieri­inde geerli de­il
024-08-15 15:14:55,950 emulator     INFO     Steam2 General Directory Server listening on port 27038

2E024-08-15 15:14:56,157 emulator     INFO     Steam2 Config Server listening on port 27035
xception in thread Thread-3:
Traceback (most recent call last):
  File "c:\python27_86\lib\threading.py", line 801, in __bootstrap_inner
  File "Y:\source\Server\emulator.py", line 319, in run
  File "Y:\source\Server\steam.py", line 703, in bind
  File "c:\python27_86\lib\socket.py", line 228, in meth
error: [Errno 10049] ¦stenen adres ieri­inde geerli de­il

E2xception in thread Thread-4:
Traceback (most recent call last):
  File "c:\python27_86\lib\threading.py", line 801, in __bootstrap_inner
  File "Y:\source\Server\emulator.py", line 319, in run
  File "Y:\source\Server\steam.py", line 703, in bind
  File "c:\python27_86\lib\socket.py", line 228, in meth
error: [Errno 10049] ¦stenen adres ieri­inde geerli de­il

024-08-15 15:14:56,362 emulator     INFO     Steam2 Master Authentication Server listening on port 27039
E2xception in thread Thread-5:
Traceback (most recent call last):
  File "c:\python27_86\lib\threading.py", line 801, in __bootstrap_inner
  File "Y:\source\Server\emulator.py", line 319, in run
  File "Y:\source\Server\steam.py", line 703, in bind
  File "c:\python27_86\lib\socket.py", line 228, in meth
error: [Errno 10049] ¦stenen adres ieri­inde geerli de­il
024-08-15 15:14:56,578 emulator     INFO     Steam2 Content List Server listening on port 27037

E2xception in thread Thread-6:
Traceback (most recent call last):
  File "c:\python27_86\lib\threading.py", line 801, in __bootstrap_inner
  File "Y:\source\Server\emulator.py", line 319, in run
  File "Y:\source\Server\steam.py", line 703, in bind
  File "c:\python27_86\lib\socket.py", line 228, in meth
error: [Errno 10049] ¦stenen adres ieri­inde geerli de­il
024-08-15 15:14:56,795 emulator     INFO     Steam2 Content Server listening on port 27030

2E024-08-15 15:14:57,012 emulator     INFO     Steam2 Client Update Server listening on port 27031
xception in thread Thread-7:
Traceback (most recent call last):
  File "c:\python27_86\lib\threading.py", line 801, in __bootstrap_inner
  File "Y:\source\Server\emulator.py", line 319, in run
  File "Y:\source\Server\steam.py", line 703, in bind
  File "c:\python27_86\lib\socket.py", line 228, in meth
error: [Errno 10049] ¦stenen adres ieri­inde geerli de­il

2E024-08-15 15:14:57,213 emulator     INFO     Steam2 User Validation Server listening on port 27040
xception in thread Thread-8:
Traceback (most recent call last):
  File "c:\python27_86\lib\threading.py", line 801, in __bootstrap_inner
  File "Y:\source\Server\emulator.py", line 319, in run
  File "Y:\source\Server\steam.py", line 703, in bind
  File "c:\python27_86\lib\socket.py", line 228, in meth
error: [Errno 10049] ¦stenen adres ieri­inde geerli de­il

E2xception in thread Thread-9:
Traceback (most recent call last):
  File "c:\python27_86\lib\threading.py", line 801, in __bootstrap_inner
  File "Y:\source\Server\steamemu\masterhl.py", line 25, in run
  File "Y:\source\Server\steam.py", line 703, in bind
  File "c:\python27_86\lib\socket.py", line 228, in meth
error: [Errno 10049] ¦stenen adres ieri­inde geerli de­il
024-08-15 15:14:57,430 emulator     INFO     Steam2 Master HL1 Server listening on port 27010

E2xception in thread Thread-10:
Traceback (most recent call last):
  File "c:\python27_86\lib\threading.py", line 801, in __bootstrap_inner
  File "Y:\source\Server\steamemu\masterhl2.py", line 24, in run
  File "Y:\source\Server\steam.py", line 703, in bind
  File "c:\python27_86\lib\socket.py", line 228, in meth
error: [Errno 10049] ¦stenen adres ieri­inde geerli de­il
024-08-15 15:14:57,635 emulator     INFO     Steam2 Master HL2 Server listening on port 27011

E2xception in thread Thread-11:
Traceback (most recent call last):
  File "c:\python27_86\lib\threading.py", line 801, in __bootstrap_inner
  File "Y:\source\Server\steamemu\masterrdkf.py", line 24, in run
  File "Y:\source\Server\steam.py", line 703, in bind
  File "c:\python27_86\lib\socket.py", line 228, in meth
error: [Errno 10049] ¦stenen adres ieri­inde geerli de­il
024-08-15 15:14:57,842 emulator     INFO     Steam2 Master RDKF Server listening on port 27012

2024-08-15 15:14:58,049 emulator     INFO     TRACKER unsupported on release client, not started
2024-08-15 15:14:58,265 emulator     INFO     Steam Web Server listening on port 80
E2xception in thread Thread-13:
Traceback (most recent call last):
  File "c:\python27_86\lib\threading.py", line 801, in __bootstrap_inner
  File "Y:\source\Server\emulator.py", line 319, in run
  File "Y:\source\Server\steam.py", line 703, in bind
  File "c:\python27_86\lib\socket.py", line 228, in meth
error: [Errno 10049] ¦stenen adres ieri­inde geerli de­il
024-08-15 15:14:58,477 emulator     INFO     Valve Time Tracking Server listening on port 27046

E2xception in thread Thread-14:
Traceback (most recent call last):
  File "c:\python27_86\lib\threading.py", line 801, in __bootstrap_inner
  File "Y:\source\Server\emulator.py", line 319, in run
  File "Y:\source\Server\steam.py", line 703, in bind
  File "c:\python27_86\lib\socket.py", line 228, in meth
error: [Errno 10049] ¦stenen adres ieri­inde geerli de­il
024-08-15 15:14:58,693 emulator     INFO     Valve CyberCafe Server listening on port 27047

2024-08-15 15:14:58,898 emulator     INFO     ...Steam Server ready...

**Comment by supervitu64** [comment]
here's a suggestion:
save your emulator configuration file and the storage, manifests and packages folder if they have stuff inside
second, delete the steam emu folder and redownload the zip, then extract 
move all the files to their correct locations in the new emulator and that should do the trick

**Comment by real-pmein1** [comment]
Error 10049 means you're trying to bing the emulator to an IP that isn't on the machine.  Presumably your server PC is on DHCP and the IP has changed, or you've put the wrong IP into the server_ip field in emulator.ini.  If you still get issues after checking those, please re-open this or raise a new case.
